-- Regulations
INSERT INTO regulations (id, name, short_name, agency, jurisdiction, description, applicable_services, processes) VALUES
(
  'aml-ctf-rules',
  'Anti-Money Laundering and Counter-Terrorism Financing Rules',
  'AML/CTF Rules',
  'AUSTRAC',
  'Australia',
  'Governs AML/CTF obligations for designated service providers in Australia, covering customer identification programs, ongoing due diligence, transaction monitoring, and suspicious matter reporting to AUSTRAC. Extended to Tranche 2 entities — including real estate agents, lawyers, and accountants — from 1 July 2026.',
  ARRAY['Banking','Remittance','Digital Currency Exchange','Financial Planning','Insurance','Superannuation'],
  '[
    {"id":"PROC-AML-001","name":"Customer Agents","description":"Procedures for collecting information about individuals authorised to act for customers — both individual and non-natural (corporate) — in relation to designated services. Covers collection of agent information and authorisation evidence, risk-based verification of agent identity for both individual and non-natural customer agents, and an optional verifying officer pathway where a nominated officer collects and validates agent details on the reporting entity''s behalf.","businessObjective":"Ensure agents acting on behalf of customers are properly identified, authorised, and assessed for ML/TF risk before transacting, preventing unauthorised access and reducing exposure from agent relationships","frequency":"once","frequencyPer":"customer","frequencyDetail":"Performed when an agent is first presented; repeated if the agent or authorisation changes","frequencyLabel":"Once per Customer Agent"},
    {"id":"PROC-AML-002","name":"Customer Due Diligence","description":"The overarching program of risk-based systems and controls for verifying customer identity across all customer types — individuals, sole traders, companies, trusts, partnerships, associations, co-operatives, and government bodies. Encompasses collection of minimum KYC information for each customer type, verification of that information using reliable and independent sources, risk-based assessment of whether additional KYC should be collected and verified, and discrepancy-handling procedures where verification reveals inconsistencies.","businessObjective":"Establish a reliable, independently verified understanding of each customer''s identity before or as soon as practicable after providing a designated service, proportionate to the ML/TF risk presented by the customer relationship","frequency":"once","frequencyPer":"customer","frequencyDetail":"Conducted at the commencement of the customer relationship; components are repeated or updated when risk indicators or regulatory triggers arise","frequencyLabel":"Once per Customer"},
    {"id":"PROC-AML-002a","name":"Onboarding — KYC Collection","parentId":"PROC-AML-002","description":"Collection of minimum KYC information at the point of customer onboarding, tailored to customer type.","businessObjective":"Collect the minimum information required to establish a customer''s identity at the start of the relationship and support subsequent verification and risk-assessment steps","frequency":"once","frequencyPer":"customer","frequencyDetail":"Performed once during initial customer onboarding, before or as soon as practicable after the provision of a designated service","frequencyLabel":"Once per Customer"},
    {"id":"PROC-AML-002b","name":"Onboarding — Verification","parentId":"PROC-AML-002","description":"Verification of collected KYC information from reliable and independent sources, using documentation (Part 4.9) or electronic data (Part 4.10), or a combination.","businessObjective":"Confirm the accuracy and authenticity of customer identity information through independent sources so the reporting entity is reasonably satisfied the customer is who they claim to be","frequency":"once","frequencyPer":"customer","frequencyDetail":"Performed during onboarding; re-verification is triggered by material changes, discrepancies, or ongoing due diligence requirements","frequencyLabel":"Once per Customer"},
    {"id":"PROC-AML-002c","name":"ML/TF Risk Assessment","parentId":"PROC-AML-002","description":"Assessment of the key ML/TF risk factors a reporting entity must consider when identifying, managing, and mitigating money laundering or terrorism financing risk.","businessObjective":"Identify, document, and manage the ML/TF risk factors inherent in the entity''s customer base and service delivery so that proportionate due diligence and program controls are applied","frequency":"ongoing","frequencyPer":"customer","frequencyDetail":"Conducted initially at onboarding; reviewed and updated regularly (at least annually or upon material change) as part of the AML/CTF program","frequencyLabel":"Ongoing per Customer"},
    {"id":"PROC-AML-003","name":"Enhanced CDD","description":"Enhanced Customer Due Diligence applied where a customer, beneficial owner, or associated person presents elevated ML/TF risk.","businessObjective":"Apply proportionate additional controls to manage elevated ML/TF risks, ensure transparency of ownership and control structures, and prevent abuse of the financial system by high-risk individuals or entities","frequency":"once","frequencyPer":"customer","frequencyDetail":"Triggered when a higher-risk indicator is identified at onboarding, during ongoing CDD, or upon risk reassessment","frequencyLabel":"Once per High-Risk Customer"},
    {"id":"PROC-AML-003a","name":"Beneficial Ownership","parentId":"PROC-AML-003","description":"The obligation to determine the beneficial owner of each customer and collect and verify each beneficial owner''s full name and either date of birth or residential address.","businessObjective":"Ensure transparency in ownership and control structures to detect and prevent misuse of entities for money laundering or terrorism financing purposes","frequency":"once","frequencyPer":"customer","frequencyDetail":"Performed during customer onboarding; updated when ownership or control structures change or as part of ongoing due diligence","frequencyLabel":"Once per Customer"},
    {"id":"PROC-AML-003b","name":"PEP Screening","parentId":"PROC-AML-003","description":"Risk-management systems to determine whether a customer or beneficial owner is a politically exposed person (PEP).","businessObjective":"Mitigate heightened corruption and ML/TF risks associated with politically exposed persons through enhanced scrutiny, senior management oversight, and source of wealth and funds checks","frequency":"once","frequencyPer":"customer","frequencyDetail":"Determined before the provision of a designated service, or as soon as practicable after; ongoing monitoring continues throughout the relationship","frequencyLabel":"Once per Customer"},
    {"id":"PROC-AML-003c","name":"Identity Verification Standards","parentId":"PROC-AML-003","description":"Verification standards applicable across CDD and ECDD. Documentary verification (Part 4.9) and Electronic verification (Part 4.10).","businessObjective":"Define the standards, methods, and controls by which the reporting entity verifies KYC information about customers and beneficial owners through reliable and independent documentation and electronic data sources","frequency":"once","frequencyPer":"customer","frequencyDetail":"Applied during CDD and ECDD verification; standards are reviewed as part of the AML/CTF program and updated when regulatory requirements change","frequencyLabel":"Once per Customer"},
    {"id":"PROC-AML-004","name":"Ongoing CDD","description":"Ongoing Customer Due Diligence process to continuously monitor customer relationships, review and update KYC information, and detect changes in risk profile or suspicious activity.","businessObjective":"Maintain an up-to-date and accurate understanding of each customer throughout the relationship so that emerging ML/TF risks are identified and managed promptly","frequency":"ongoing","frequencyPer":"customer","frequencyDetail":"Continuous monitoring with periodic reviews and updates triggered by events, risk indicators, or changes in the customer''s circumstances","frequencyLabel":"Ongoing per Customer"},
    {"id":"PROC-AML-004a","name":"High Value Transactions","parentId":"PROC-AML-004","description":"Monitoring and reporting of transactions at or above prescribed thresholds, including threshold transaction reports (TTRs) for cash transactions of AUD 10,000 or more.","businessObjective":"Detect and report high-value transactions that may indicate money laundering or terrorism financing, ensuring threshold reporting obligations to AUSTRAC are met within prescribed timeframes","frequency":"ongoing","frequencyPer":"transaction","frequencyDetail":"Monitored in real-time or near real-time for each transaction; TTRs submitted within prescribed timeframes","frequencyLabel":"Ongoing per Transaction"},
    {"id":"PROC-AML-004b","name":"Suspicious Matter Reporting","parentId":"PROC-AML-004","description":"Process of identifying and reporting suspicious matters to AUSTRAC in accordance with the AML/CTF Act.","businessObjective":"Identify and escalate potentially illicit activity to AUSTRAC through timely suspicious matter reports, contributing to the detection and disruption of money laundering and terrorism financing","frequency":"ongoing","frequencyPer":"customer","frequencyDetail":"Triggered by suspicious activity identified during transaction monitoring, ongoing CDD, or risk reassessment; SMRs submitted within prescribed timeframes","frequencyLabel":"Ongoing per Customer"}
  ]'::jsonb
),
(
  'privacy-act-1988',
  'Privacy Act 1988 — Australian Privacy Principles',
  'Privacy Act (APPs)',
  'OAIC',
  'Australia',
  'The Australian Privacy Principles (APPs) set out the obligations of Australian Government agencies and private sector organisations with an annual turnover above $3 million (and certain others) in relation to the collection, use, disclosure, quality, security, and individual access to personal information.',
  ARRAY['Banking','Insurance','Superannuation','Healthcare','Telecommunications','Retail','Technology','Financial Planning'],
  '[
    {"id":"PROC-PRIV-001","name":"Privacy Governance","description":"Establishing and maintaining the governance framework for privacy compliance, including designating a privacy officer, maintaining a privacy policy, conducting privacy impact assessments for new initiatives, and training staff on privacy obligations under the Privacy Act 1988.","businessObjective":"Embed privacy accountability across the organisation so that personal information handling obligations are understood, assigned, and systematically met","frequency":"ongoing","frequencyPer":"organisation","frequencyDetail":"Policy reviewed annually or upon material change to data handling practices or regulatory requirements","frequencyLabel":"Ongoing"},
    {"id":"PROC-PRIV-001a","name":"Privacy Policy Management","parentId":"PROC-PRIV-001","description":"Maintaining a clearly expressed, up-to-date privacy policy that describes the kinds of personal information collected, how it is collected, held, used, and disclosed, how individuals may access and correct their information, and how to make a privacy complaint.","businessObjective":"Satisfy APP 1 transparency obligations and provide individuals with a clear and accessible account of how their personal information is managed","frequency":"ongoing","frequencyPer":"organisation","frequencyDetail":"Reviewed at least annually and updated whenever handling practices change materially","frequencyLabel":"Annual Review"},
    {"id":"PROC-PRIV-001b","name":"Privacy Impact Assessments","parentId":"PROC-PRIV-001","description":"Conducting privacy impact assessments (PIAs) for new projects, systems, or data flows that involve the collection or handling of personal information, identifying privacy risks and implementing mitigations before the initiative is launched.","businessObjective":"Proactively identify and mitigate privacy risks in new initiatives before personal information is collected or systems are deployed","frequency":"once","frequencyPer":"project","frequencyDetail":"Performed prior to launch of any new product, service, or system that involves personal information handling","frequencyLabel":"Once per Project"},
    {"id":"PROC-PRIV-002","name":"Collection and Notification","description":"Ensuring personal information is only collected where reasonably necessary for the entity''s functions, that collection methods are lawful and fair, and that individuals are notified of key collection details at or before the time of collection in accordance with APPs 3–5.","businessObjective":"Limit collection to what is genuinely required and ensure individuals are fully informed about how their personal information will be used at the point of collection","frequency":"once","frequencyPer":"customer","frequencyDetail":"Performed at the point of initial collection; collection notices reviewed annually or when purposes change","frequencyLabel":"Once per Customer"},
    {"id":"PROC-PRIV-003","name":"Use and Disclosure Controls","description":"Controls governing the use and disclosure of personal information, ensuring it is only used or disclosed for the primary purpose of collection or a permitted secondary purpose (APP 6).","businessObjective":"Prevent unauthorised use or disclosure of personal information and ensure all secondary uses are within the boundaries permitted by the APPs","frequency":"ongoing","frequencyPer":"transaction","frequencyDetail":"Applied at each point of use or disclosure; direct marketing lists reviewed quarterly; cross-border agreements reviewed annually","frequencyLabel":"Ongoing per Transaction"},
    {"id":"PROC-PRIV-004","name":"Data Quality and Security","description":"Processes to maintain the accuracy, completeness, and currency of personal information before use or disclosure (APP 10), and to protect personal information from misuse, interference, loss, and unauthorised access through appropriate technical and organisational security measures (APP 11).","businessObjective":"Ensure personal information remains accurate and is protected against unauthorised access or loss throughout its lifecycle, and that eligible data breaches are identified and notified promptly","frequency":"ongoing","frequencyPer":"organisation","frequencyDetail":"Security controls reviewed annually; data quality checks applied before material use or disclosure; breach response tested at least annually","frequencyLabel":"Ongoing"},
    {"id":"PROC-PRIV-004a","name":"Notifiable Data Breaches","parentId":"PROC-PRIV-004","description":"Procedures for assessing and responding to suspected data breaches in accordance with the Notifiable Data Breaches (NDB) scheme under Part IIIC of the Privacy Act 1988.","businessObjective":"Meet statutory notification obligations under the NDB scheme and minimise harm to individuals by responding promptly and transparently to eligible data breaches","frequency":"once","frequencyPer":"incident","frequencyDetail":"Triggered upon becoming aware of a suspected eligible data breach; OAIC notification required within 30 days of awareness","frequencyLabel":"Once per Incident"},
    {"id":"PROC-PRIV-005","name":"Individual Rights Management","description":"Processes for handling individual requests to access (APP 12) and correct (APP 13) their personal information.","businessObjective":"Uphold individuals'' rights over their personal information by providing timely access and correction, and resolving privacy complaints fairly and efficiently","frequency":"once","frequencyPer":"request","frequencyDetail":"Handled on receipt; access provided within 30 days (or extended with notice); complaints acknowledged within 30 days","frequencyLabel":"Once per Request"}
  ]'::jsonb
);

-- Regulation key dates
INSERT INTO regulation_key_dates (id, regulation_id, title, description, iso_date, recurrence, is_countdown_primary, sort_order) VALUES
('aml-annual-report', 'aml-ctf-rules', 'Annual Compliance Report', 'Submit the Annual Compliance Report to AUSTRAC covering the preceding calendar year. All reporting entities must complete this via AUSTRAC Online by 31 March each year.', '2026-03-31', 'annual', TRUE, 0),
('aml-tranche2-start', 'aml-ctf-rules', 'Tranche 2 Obligations Commence', 'Extended AML/CTF obligations apply to real estate agents and developers, lawyers, conveyancers, accountants, and trust & company service providers from this date.', '2026-07-01', 'once', FALSE, 1),
('aml-program-review', 'aml-ctf-rules', 'AML/CTF Program Annual Review', 'Complete the mandatory annual review and update of the AML/CTF Program, including risk assessments, Part A and Part B controls, and board sign-off.', '2026-12-31', 'annual', FALSE, 2),
('priv-compliance-review', 'privacy-act-1988', 'Annual Privacy Compliance Review', 'Conduct the annual privacy compliance review: audit personal information holdings, update the privacy policy, verify staff training records, and review PIA outcomes.', '2026-06-30', 'annual', TRUE, 0),
('priv-pia-review', 'privacy-act-1988', 'Privacy Impact Assessment Review', 'Review privacy impact assessments for all active projects and systems that handle personal information, and remediate any identified privacy risks.', '2026-09-30', 'annual', FALSE, 1),
('priv-staff-training', 'privacy-act-1988', 'Staff Privacy Training', 'Complete annual privacy awareness training for all staff with access to personal information. Record completion for audit purposes.', '2026-11-30', 'annual', FALSE, 2);

-- Calendar events
INSERT INTO calendar_events (id, title, date_label, regulation_id, agency, description) VALUES
('cal-aml-annual', 'Annual AML Compliance Report', 'MAR 31', 'aml-ctf-rules', 'AUSTRAC', 'Mandatory 2025/26 Review'),
('cal-motor-finance', 'Motor Finance Redress Deadline', 'MAY 31', NULL, 'FCA', 'Final response period ends'),
('cal-tranche2', 'Tranche 2 Obligations Start', 'JUL 01', 'aml-ctf-rules', 'AUSTRAC', 'Real Estate/Legal sectors captured'),
('cal-eu-ai', 'EU AI Act Enforcement', 'AUG 02', NULL, 'GDPR/EC', 'High-risk AI obligations apply'),
('cal-privacy-audit', 'Annual Privacy Audit', 'SEP 15', NULL, 'GDPR', 'DPO internal review due');
